# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.runs/synth_1/.Xil/Vivado-25204-dorn_pc/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    set rt::partid xc7a35tcpg236-1

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib

    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv {
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/keypad_logic_module.sv
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/imports/new/ti85_display_module.sv
    }
      rt::read_verilog {
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/imports/samue/lab_4_task_q/lab_4_task_q.srcs/sources_1/new/debouncer.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/debouncer_parent.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/graphing_calculator_top.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/menu_logic_module.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/equation_input_module.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/clocking_functions.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/graph_plotter.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/project_top.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/home_screen.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/imports/new/text_renderer.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/imports/new/small_font_rom.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/imports/new/font_rom.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/imports/new/Top_Student.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/imports/new/game_state.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/imports/new/game_display.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/imports/new/flexible_clock.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/calculator_fsm.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/output_screen_renderer.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/add_function.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/multiply_function.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/subtract_function.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/divide_function.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/oled_display.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/input_screen_renderer.v
      C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.srcs/sources_1/new/dual_oled_calculator_pixel.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.runs/synth_1/.Xil/Vivado-25204-dorn_pc/realtime/project_top_synth.xdc
    rt::sdcChecksum
    set rt::top project_top
    rt::set_parameter enableIncremental true
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.cache/wt}
    rt::set_parameter enableSplitFlowPath "C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.runs/synth_1/.Xil/Vivado-25204-dorn_pc/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
