# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.cache/wt [current_project]
set_property parent.project_path C:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/samue/Documents/vivado/ee2026_b02_g10/FDP.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/samue/lab_4_task_q/lab_4_task_q.srcs/sources_1/new/colour_identifier.v
  C:/Users/samue/lab_4_task_q/lab_4_task_q.srcs/sources_1/new/debouncer.v
  C:/Users/samue/lab_4_task_q/lab_4_task_q.srcs/sources_1/new/freq_clock_gen.v
  C:/Users/samue/lab_4_task_q/lab_4_task_q.srcs/sources_1/new/oled_display.v
  C:/Users/samue/lab_4_task_q/lab_4_task_q.srcs/sources_1/new/pixel_output_generator.v
  C:/Users/samue/lab_4_task_q/lab_4_task_q.srcs/sources_1/new/task_q.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/samue/lab_4_task_q/lab_4_task_q.srcs/constrs_1/new/my_basys3_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/samue/lab_4_task_q/lab_4_task_q.srcs/constrs_1/new/my_basys3_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top task_q -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef task_q.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file task_q_utilization_synth.rpt -pb task_q_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
