# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/My-Work/NUS/Y2S1/EE2026/Project/Basic-Tasks/project-poly/project-poly.cache/wt [current_project]
set_property parent.project_path C:/My-Work/NUS/Y2S1/EE2026/Project/Basic-Tasks/project-poly/project-poly.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/My-Work/NUS/Y2S1/EE2026/Project/Basic-Tasks/project-poly/project-poly.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/My-Work/NUS/Y2S1/EE2026/Project/Project/ee2026_b02_g10/FDP.srcs/sources_1/new/add_function.v
  C:/My-Work/NUS/Y2S1/EE2026/Project/Project/ee2026_b02_g10/FDP.srcs/sources_1/new/calculator_fsm.v
  C:/My-Work/NUS/Y2S1/EE2026/Project/Project/ee2026_b02_g10/FDP.srcs/sources_1/new/debounce.v
  C:/My-Work/NUS/Y2S1/EE2026/Project/Project/ee2026_b02_g10/FDP.srcs/sources_1/new/divide_function.v
  C:/My-Work/NUS/Y2S1/EE2026/Project/Project/ee2026_b02_g10/FDP.srcs/sources_1/new/freq_6_25m.v
  C:/My-Work/NUS/Y2S1/EE2026/Project/Project/ee2026_b02_g10/FDP.srcs/sources_1/new/input_screen_renderer.v
  C:/My-Work/NUS/Y2S1/EE2026/Project/Project/ee2026_b02_g10/FDP.srcs/sources_1/new/multiply_function.v
  C:/My-Work/NUS/Y2S1/EE2026/Project/Project/ee2026_b02_g10/FDP.srcs/sources_1/new/oled_display.v
  C:/My-Work/NUS/Y2S1/EE2026/Project/Project/ee2026_b02_g10/FDP.srcs/sources_1/new/output_screen_renderer.v
  C:/My-Work/NUS/Y2S1/EE2026/Project/Project/ee2026_b02_g10/FDP.srcs/sources_1/new/subtract_function.v
  C:/My-Work/NUS/Y2S1/EE2026/Project/Project/ee2026_b02_g10/FDP.srcs/sources_1/new/dual_oled_calculator_top.v
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/My-Work/NUS/Y2S1/EE2026/Project/Project/ee2026_b02_g10/FDP.srcs/constrs_1/imports/new/my_basys3_constraints.xdc
set_property used_in_implementation false [get_files C:/My-Work/NUS/Y2S1/EE2026/Project/Project/ee2026_b02_g10/FDP.srcs/constrs_1/imports/new/my_basys3_constraints.xdc]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top dual_oled_calculator_top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef dual_oled_calculator_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file dual_oled_calculator_top_utilization_synth.rpt -pb dual_oled_calculator_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
