//////////////////////////////////////////////////////////////////////////////////
// Engineer:      (Generated by Gemini)
// Create Date:   10/07/2025
// Module Name:   mode_of_operation
// Description:
// Acts as a multiplexer to select the result from one of the four arithmetic
// modules based on the `mode_of_operation` input.
//////////////////////////////////////////////////////////////////////////////////
module mode_of_operation (
    input [1:0] mode_of_operation,
    input [16:0] num1, num2,
    output reg [19:0] num3
);

    // Wires for the output of each arithmetic function
    wire [19:0] add_result, sub_result, div_result, mul_result;

    // Instantiate all arithmetic functions
    add_function      adder (.num_1(num1), .num_2(num2), .num_3(add_result));
    subtract_function subber(.num_1(num1), .num_2(num2), .num_3(sub_result));
    divide_function   divider(.num_1(num1), .num_2(num2), .num_3(div_result));
    multiply_function multer(.num_1(num1), .num_2(num2), .num_3(mul_result));

    // Select the final output based on the mode
    always @(*) begin
        case(mode_of_operation)
            2'b00: num3 = add_result; // Add
            2'b01: num3 = sub_result; // Subtract
            2'b10: num3 = div_result; // Divide
            2'b11: num3 = mul_result; // Multiply
            default: num3 = 20'd0;
        endcase
    end

endmodule
