//////////////////////////////////////////////////////////////////////////////////
// Engineer:      (Generated by Gemini)
// Create Date:   10/11/2025
// Module Name:   dual_oled_calculator_top
// Description:
//
// This is the definitive top-level module for the dual-display calculator. It
// has been updated to instantiate the OLED drivers with a FLIP_SCREEN
// parameter, allowing for individual screen orientation control.
//
//////////////////////////////////////////////////////////////////////////////////
module dual_oled_calculator_top(
    input clk,
    input btnC_raw, btnU_raw, btnD_raw, btnL_raw, btnR_raw,

    // Pmod ports defined as 8-bit buses to match the XDC file
    output [7:0] JA,
    output [7:0] JB
);

    //================================================================
    // Intermediate Wires for all signals
    //================================================================
    wire slow_clk;
    wire manual_reset_req;
    wire master_reset;
    wire btn_C_p, btn_U_p, btn_D_p, btn_L_p, btn_R_p;
    wire [2:0]  current_state;
    wire [16:0] num1, num2;
    wire [19:0] result;
    wire [1:0]  op_code, op_selection;
    wire [3:0]  numpad_selection;
    wire [15:0] pixel_data_a, pixel_data_b;
    wire [12:0] pixel_index_a, pixel_index_b;
    wire ja_cs_wire, ja_sdin_wire, ja_sclk_wire, ja_dc_wire, ja_res_wire, ja_vccen_wire, ja_pmoden_wire;
    wire jb_cs_wire, jb_sdin_wire, jb_sclk_wire, jb_dc_wire, jb_res_wire, jb_vccen_wire, jb_pmoden_wire;

    //================================================================
    // Clocking and Reset Logic
    //================================================================
    freq_6_25m clock_divider ( .clk(clk), .slow_clk(slow_clk) );

    reg [15:0] reset_counter = 16'hFFFF;
    wire power_on_reset = |reset_counter;

    always @(posedge clk) begin
        if (power_on_reset) begin
            reset_counter <= reset_counter - 1;
        end
    end

    assign master_reset = power_on_reset || manual_reset_req;

    //================================================================
    // Button Debouncing (Using the robust 'debounce' module)
    //================================================================
    debounce debounce_C ( .clk(clk), .pb_1(btnC_raw), .pb_out(btn_C_p) );
    debounce debounce_U ( .clk(clk), .pb_1(btnU_raw), .pb_out(btn_U_p) );
    debounce debounce_D ( .clk(clk), .pb_1(btnD_raw), .pb_out(btn_D_p) );
    debounce debounce_L ( .clk(clk), .pb_1(btnL_raw), .pb_out(btn_L_p) );
    debounce debounce_R ( .clk(clk), .pb_1(btnR_raw), .pb_out(btn_R_p) );

    //================================================================
    // Core FSM and Renderer Instantiations
    //================================================================
    calculator_fsm fsm (
        .clk(slow_clk), .reset(master_reset),
        .btnC(btn_C_p), .btnU(btn_U_p), .btnD(btn_D_p), .btnL(btn_L_p), .btnR(btn_R_p),
        .manual_reset_req(manual_reset_req), .current_state(current_state),
        .num1_out(num1), .num2_out(num2), .result_out(result),
        .op_code_out(op_code), .op_selection_out(op_selection),
        .numpad_selection_out(numpad_selection)
    );

    output_screen_renderer renderer_a (
        .pixel_index(pixel_index_a), .state(current_state),
        .num1(num1), .num2(num2), .result(result), .op_code(op_code),
        .pixel_data(pixel_data_a)
    );

    input_screen_renderer renderer_b (
        .pixel_index(pixel_index_b), .state(current_state),
        .op_selection(op_selection), .numpad_selection(numpad_selection),
        .pixel_data(pixel_data_b)
    );

    //================================================================
    // OLED Driver Instantiations with FLIP_SCREEN Parameter
    //================================================================

    // Screen A (Output) on Pmod JA - Flipped 180 degrees
    oled_display #(
        .FLIP_SCREEN(1)
    ) oled_a (
        .clk(slow_clk), .reset(master_reset), .pixel_index(pixel_index_a), .pixel_data(pixel_data_a),
        .cs(ja_cs_wire), .sdin(ja_sdin_wire), .sclk(ja_sclk_wire),
        .d_cn(ja_dc_wire), .resn(ja_res_wire), .vccen(ja_vccen_wire), .pmoden(ja_pmoden_wire)
    );

    // Screen B (Input) on Pmod JB - Normal orientation
    oled_display #(
        .FLIP_SCREEN(0)
    ) oled_b (
        .clk(slow_clk), .reset(master_reset), .pixel_index(pixel_index_b), .pixel_data(pixel_data_b),
        .cs(jb_cs_wire), .sdin(jb_sdin_wire), .sclk(jb_sclk_wire),
        .d_cn(jb_dc_wire), .resn(jb_res_wire), .vccen(jb_vccen_wire), .pmoden(jb_pmoden_wire)
    );

    //================================================================
    // Final Output Pin Mapping
    //================================================================
    assign JA[0] = ja_cs_wire; assign JA[1] = ja_sdin_wire; assign JA[2] = 1'b0; assign JA[3] = ja_sclk_wire;
    assign JA[4] = ja_dc_wire; assign JA[5] = ja_res_wire; assign JA[6] = ja_vccen_wire; assign JA[7] = ja_pmoden_wire;

    assign JB[0] = jb_cs_wire; assign JB[1] = jb_sdin_wire; assign JB[2] = 1'b0; assign JB[3] = jb_sclk_wire;
    assign JB[4] = jb_dc_wire; assign JB[5] = jb_res_wire; assign JB[6] = jb_vccen_wire; assign JB[7] = jb_pmoden_wire;

endmodule
